### ISSUE TITLE
Can not connect to redux

### ISSUE THREAD

**Issue by bradennapier** [AlexeyFrolov/react-layer-stack#12]
Can you show example of using our own reducer?  Apparently it doesnt work

mapStateToProps() in Connect(Component) must return a plain object. Instead received undefined.

**Comment by lexfrl** [comment]
Your "own store", you mean? You can combine the reducer (`import { reducer as layersReducer } from 'react-layer-stack'`) using `combineReducers`:

https://github.com/fckt/react-layer-stack/blob/589f173a66581753a4977b4b74aed9b66d55c9d0/demo/src/App.js#L12

If it's not an answer to your Q, please, provide more information
