### ISSUE TITLE
Add function aliases 

### ISSUE THREAD

**Issue by smeijer** [AlexeyFrolov/react-layer-stack#6]
Awesome library! Thanks.

I only find the function names: `showMe`, `hideMe` and `showOnlyMe` a little "childish". (Sorry, I don't know how to say it otherwise).

```js
callback({ isActive, showMe: callback(args), showOnlyMe, hideMe, hideAll })
```

Can these be aliased? This is what I'm thinking about:

`showMe` » `add`
I guess this one should be called `add`. Because this function will `add` the element to the DOM, and not just setting a style to make it visible.

`showOnlyMe` » `set`
The LayerContext is being `set` to display this layer, instead of `adding` it to the context. 

`hideMe` » `remove`
I would call it `remove`. Because this function will `remove` the element from the DOM, and not just setting a style to make it invisible.

`hideAll` » `reset`
I would call it `reset` or `clear`. If you don't like that name; you can also go with `removeAll`.

**Comment by lexfrl** [comment]
thanks for your question and for the feedback! Good to know that you've found it useful for you. 
I'll answer to your question tomorrow in detail, if you will, a lot of things to do today..

**Comment by lexfrl** [comment]
I understand the problem. I have some ideas on how to make better naming.

**Comment by lexfrl** [comment]
As you can see, historically we have:
https://github.com/fckt/react-layer-stack/blob/master/src/components.js#L99
hide

`hideMe()` are `showMe(...args)` are aliases for hide(id) and show(id, ...args)

Here is the deal.
 At first, I'll remove `hide` and `show` rename `hideMe` to `hide` and `showMe` to `show`. 
Second, I'll add a new component: <Layer**s**Context /> and move current `hide(id)` and `show(id)` to it.

**Comment by smeijer** [comment]
Do you need a component for the `show(id)`? 

I guess it can be made so it defaults to the current layer when the ID argument is left blank, and set to a target layer when ID is provided? 

Isn't something like that more convenient? I'm just thinking out loud. Ignore me if it doesn't make sense.

**Comment by lexfrl** [comment]
> I guess it can be made so it defaults to the current layer when the ID argument is left blank, and set to a target layer when ID is provided?

Definitely I love the idea! I think also, maybe better to make it on the `props` level. If an `id` prop (to LayerContext) is not provided - do not prepopulate `show` with an `id`. One thing, I not sure, is that: will it be clear enough for user.. I guess, that it could feel natural and pretty logical: if you didn't specify the `id`, user shouldn't expect that `show` will receive it.. But what we should do is: if user make a mistake, there should be a good explanation of what is going on and how to avoid the problem.. I think, we can add an error like: "the is no Layer with id=[some id]" with explanations, what to do next and how to fix it.

**Comment by lexfrl** [comment]
I'm so sorry, I was planning to make a new release with the changes last week, but I'm currently in the process of moving to another city, these was a lot of things to be done, physically.. I'll try hard to ship it as soon as possible! Thank you for your participation and patience!

**Comment by lexfrl** [comment]
I created a chat also, I'm online to discuss all things around! https://gitter.im/react-layer-stack/Lobby

**Comment by lexfrl** [comment]
done! Now it's 2.0.0
https://github.com/fckt/react-layer-stack/commit/8e7a7f8a04a739f76569789ac83af44549ed2d53
